## Server
server:
  port: 8080
  max-http-header-size: 20000
  servlet:
    context-path: /api

## Database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://blockduce.c0pmibo6dwxp.ap-northeast-2.rds.amazonaws.com:3306/blockduce?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: j4b107blockduce!!

  jpa:
    # generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #    hiberanate:
    #      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# AWS S3
cloud:
  aws:
    credentials:
      accessKey: AKIAYL2LDM2UCG2IVBEY
      secretKey: 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
    s3:
      bucket: blockduce-image
    region:
      static: ap-northeast-2
    stack:
      auto: false